spring:
  application:
    name: replication

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

rabbitmq:
  exchange:
     name: ${EXCHANGE_NAME}

custom:
  rabbitmq:
    queues:
      - ${QUEUE_NAME_1}
      - ${QUEUE_NAME_2}
      - ${QUEUE_NAME_3}